### ISSUE TITLE
Use OpenPrinting CUPS

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub/org.chromium.Chromium#115]
Since Chrome, Edge and Brave have switched to OpenPrinting CUPS, this one should as well.

**Comment by vchernin** [comment]
Probably worth adding an x-checker-data entry for OpenPrinting CUPS too, since it's GitHub repo is nicely tracked for us by [release-monitoring.org](https://release-monitoring.org/project/380/) ([which f-e-d-c supports](https://github.com/flathub/flatpak-external-data-checker#anitya-release-monitoring-checker)).

Also, should this be using the ["op" releases/tags](https://github.com/OpenPrinting/cups/releases) of CUPS? Currently Anitya marks them as "pre-release" but maybe we actually want them, it seems like a lot of improvements have been made since OpenPrinting CUPS forked.

**Comment by Erick555** [comment]
op -> OpenPrinting . Using op tags is exct point if this issue :smile:
