### ISSUE TITLE
Why the downgrade back to llvm11?

### ISSUE THREAD

**Issue by rany2** [flathub/org.chromium.Chromium#116]
What prompted you to downgrade back to llvm11? 

https://github.com/flathub/org.chromium.Chromium/commit/63f22bbede2760369ffcd9253d7e52ac65fc89c9

**Comment by refi64** [comment]
Our build is cursed and [crashed LLVM 12](https://github.com/flathub/org.chromium.Chromium/pull/113#issuecomment-849225240). I've spent some time researching solutions but can't find any references to this bug, nor any changes in the relevant files that would indicate how it was fixed in the LLVM versions Chromium uses.

That being said, the downgrade is temporary until we can find a better solution. Currently I'm considering caving in to building the Chromium toolchain in #117 which should be a fix.

**Comment by rany2** [comment]
Thanks, I see it's not an ideal "temporary solution" but its better than 
Chromium becoming out of date and leaving users vulnerable to security 
vulnerabilities.
