### ISSUE TITLE
VAAPI seems to stopped working with latest release (95.0.4638.54)

### ISSUE THREAD

**Issue by apawelec** [flathub/org.chromium.Chromium#169]
After latest Chromium upgrade all media are rendered with software _FFmpegVideoDecoder_ and `intel_gpu_top` confirms that GPU is no longer is use. 

I'm running Chromium with flags: `--enable-features=VaapiVideoDecoder --zero-copy --enable-gpu-rasterization --ignore-gpu-blocklist` and env variable `LIBVA_DRIVER_NAME=iHD` - in previous versions it resulted with properly working hardware video decode.

**Comment by methane4** [comment]
![Screenshot from 2021-11-04 00-28-05](https://user-images.githubusercontent.com/46012160/140237334-cfd56e51-deaa-4b61-8c3f-65e42cba5884.png)

Also, when the fix comes there should be instructions on the wiki on how to enable it properly

**Comment by wooque** [comment]
Here is the patch from ArchLinux, it applies cleanly to v95 
https://raw.githubusercontent.com/archlinux/svntogit-packages/packages/chromium/trunk/ozone-x11-fix-VA-API.patch

**Comment by mayhd3** [comment]
Here is a working downgraded environment if it helps anyone:
* Fedora 35
* amdgpu
* libva `2.13.0-1.fc35`
* flathub chromium `94.0.4606.81` from commit `e5bad1c90caa1e73240afacdae18416e439df151c8832e26dbce7ce028f2475`
* `--enable-features=VaapiVideoDecoder`

![image](https://user-images.githubusercontent.com/9441877/140461550-131acea5-afce-48f1-ba74-69e85c41e619.png)

![image](https://user-images.githubusercontent.com/9441877/140461574-6deb0ad1-1aaf-4922-839a-cc48b068501a.png)

using `--disable-features=UseOzonePlatform` adds more entries to the "Video Acceleration Information" table, but also causes VDAVideoDecoder to stop being selected when I actually inspect a video in the media menu or media-internals...

**Comment by Erick555** [comment]
Note that downgrading version would make you vulnerable for security issues fixed in the latest one.

**Comment by apawelec** [comment]
> Note that downgrading version would make you vulnerable for security issues fixed in the latest one.

Yeah, of course you're right, but to be honest, I prefer my business Dell not to melt down when watching any video on browser ;)

**Comment by apawelec** [comment]
Fixed in yesterday upgrade to Chromium 96.

**Comment by alvarlagerlof** [comment]
Is there any way to use this on an Intel cpu on a system that also has a nvidia gpu?

**Comment by methane4** [comment]
hardware decoding of AV1 isnt working for me, resulting in a hit or miss for hardware decoded videos while using youtube. Is anyone else having the same issue?

**Comment by Schlipak** [comment]
Same here, Intel CPU with an NVIDIA GPU (GeForce RTX 2060) running the official non-free driver (470). Hardware acceleration worked fine before v94, broke in v95 with only Swiftshader CPU fallback, now in v96 it's completely broken, Chromium can't communicate with my GPU anymore. Chrome stable (non-flatpak) works.

Here's my chrome://gpu dump :
<details>
<summary>Show dump</summary>

<div style="box-sizing: border-box; user-select: text; margin-bottom: 1em; color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="button" id="copy-to-clipboard" value="Copy Report to Clipboard" style="box-sizing: border-box; user-select: none; appearance: none; background-image: -webkit-linear-gradient(top, rgb(240, 240, 240), rgb(240, 240, 240) 38%, rgb(224, 224, 224)); border: 1px solid rgb(77, 144, 254); border-radius: 2px; box-shadow: rgba(0, 0, 0, 0.12) 0px 1px 0px, rgba(255, 255, 255, 0.95) 0px 1px 2px inset; color: black; font: inherit; margin: 0px 1px 0px 0px; outline: none; text-shadow: rgb(240, 240, 240) 0px 1px 0px; min-height: 2em; min-width: 4em; padding-bottom: 1px; padding-top: 1px; padding-inline: 10px; transition: border-color 200ms ease 0s;"></div><div style="box-sizing: border-box; user-select: text; margin-bottom: 1em; color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3 style="box-sizing: border-box; user-select: text; margin-bottom: 0px; margin-top: 0px;">Graphics Feature Status</h3><ul class="feature-status-list" style="box-sizing: border-box; user-select: text; margin-bottom: 0px; margin-top: 0px;"><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Canvas:<span> </span></span><span class="feature-yellow" style="box-sizing: border-box; user-select: text; color: rgb(128, 128, 0);">Software only. Hardware acceleration disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Canvas out-of-process rasterization:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Compositing:<span> </span></span><span class="feature-yellow" style="box-sizing: border-box; user-select: text; color: rgb(128, 128, 0);">Software only. Hardware acceleration disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Multiple Raster Threads:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Out-of-process Rasterization:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">OpenGL:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Rasterization:<span> </span></span><span class="feature-yellow" style="box-sizing: border-box; user-select: text; color: rgb(128, 128, 0);">Software only. Hardware acceleration disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Raw Draw:<span> </span></span><span class="feature-yellow" style="box-sizing: border-box; user-select: text; color: rgb(128, 128, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Skia Renderer:<span> </span></span><span class="feature-green" style="box-sizing: border-box; user-select: text; color: rgb(0, 128, 0);">Enabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Video Decode:<span> </span></span><span class="feature-yellow" style="box-sizing: border-box; user-select: text; color: rgb(128, 128, 0);">Software only. Hardware acceleration disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Vulkan:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">WebGL:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">WebGL2:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li></ul></div><div class="problems-div" style="box-sizing: border-box; user-select: text; margin-bottom: 1em; color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3 style="box-sizing: border-box; user-select: text; margin-bottom: 0px; margin-top: 0px;">Problems Detected</h3><ul class="problems-list" style="box-sizing: border-box; user-select: text; margin-bottom: 0px; margin-top: 0px;"><li style="box-sizing: border-box; user-select: text;"><a style="box-sizing: border-box; user-select: text;">Accelerated video decode has been disabled, either via blocklist, about:flags or the command line.</a><br style="box-sizing: border-box; user-select: text;"><i style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Disabled Features:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">video_decode</span></i></li><li style="box-sizing: border-box; user-select: text;"><a style="box-sizing: border-box; user-select: text;">Gpu compositing has been disabled, either via blocklist, about:flags or the command line. The browser will fall back to software compositing and hardware acceleration will be unavailable.</a><br style="box-sizing: border-box; user-select: text;"><i style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Disabled Features:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">gpu_compositing</span></i></li><li style="box-sizing: border-box; user-select: text;"><a style="box-sizing: border-box; user-select: text;">GPU process was unable to boot: GPU process crashed too many times with SwiftShader.</a><br style="box-sizing: border-box; user-select: text;"><i style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Disabled Features:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">all</span></i></li></ul></div><div style="box-sizing: border-box; user-select: text; margin-bottom: 1em; color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3 style="box-sizing: border-box; user-select: text; margin-bottom: 0px; margin-top: 0px;">Version Information</h3><div id="client-info" style="box-sizing: border-box; user-select: text;"><div jstcache="0" style="box-sizing: border-box; user-select: text;">

Data exported | 2021-11-23T09:21:22.733Z
-- | --
Chrome version | Chrome/96.0.4664.45
Operating system | Linux 5.4.0-90-generic
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/76e4c1bb2ab4671b8beba3444e61c0f17584b2fc/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/76e4c1bb2ab4671b8beba3444e61c0f17584b2fc/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | unknown hash
2D graphics backend | Skia/96 eca463eb20a11c3c569304228ede2adb29a4228b
Command Line | /app/chromium/chrome --enable-features=OverlayScrollbarFlashWhenMouseEnter,OverlayScrollbarFlashAfterAnyScrollUpdate,OverlayScrollbar --disable-features=WebAssemblyTrapHandler --enable-crashpad --flag-switches-begin --ignore-gpu-blocklist --flag-switches-end --origin-trial-disabled-features=CaptureHandle

</div></div></div><div class="feature-status-for-hardware-gpu-div" style="box-sizing: border-box; user-select: text; margin-bottom: 1em; color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3 style="box-sizing: border-box; user-select: text; margin-bottom: 0px; margin-top: 0px;">Graphics Feature Status for Hardware GPU</h3><ul class="feature-status-for-hardware-gpu-list" style="box-sizing: border-box; user-select: text; margin-bottom: 0px; margin-top: 0px;"><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Canvas:<span> </span></span><span class="feature-yellow" style="box-sizing: border-box; user-select: text; color: rgb(128, 128, 0);">Software only. Hardware acceleration disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Canvas out-of-process rasterization:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Compositing:<span> </span></span><span class="feature-yellow" style="box-sizing: border-box; user-select: text; color: rgb(128, 128, 0);">Software only. Hardware acceleration disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Multiple Raster Threads:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Out-of-process Rasterization:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">OpenGL:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Rasterization:<span> </span></span><span class="feature-yellow" style="box-sizing: border-box; user-select: text; color: rgb(128, 128, 0);">Software only. Hardware acceleration disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Raw Draw:<span> </span></span><span class="feature-yellow" style="box-sizing: border-box; user-select: text; color: rgb(128, 128, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Skia Renderer:<span> </span></span><span class="feature-green" style="box-sizing: border-box; user-select: text; color: rgb(0, 128, 0);">Enabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Video Decode:<span> </span></span><span class="feature-yellow" style="box-sizing: border-box; user-select: text; color: rgb(128, 128, 0);">Software only. Hardware acceleration disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Vulkan:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">WebGL:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">WebGL2:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li></ul></div><div class="problems-for-hardware-gpu-div" style="box-sizing: border-box; user-select: text; margin-bottom: 1em; color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3 style="box-sizing: border-box; user-select: text; margin-bottom: 0px; margin-top: 0px;">Problems Detected for Hardware GPU</h3><ul class="problems-for-hardware-gpu-list" style="box-sizing: border-box; user-select: text; margin-bottom: 0px; margin-top: 0px;"><li style="box-sizing: border-box; user-select: text;"><a style="box-sizing: border-box; user-select: text;">Accelerated video decode has been disabled, either via blocklist, about:flags or the command line.</a><br style="box-sizing: border-box; user-select: text;"><i style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Disabled Features:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">video_decode</span></i></li><li style="box-sizing: border-box; user-select: text;"><a style="box-sizing: border-box; user-select: text;">Gpu compositing has been disabled, either via blocklist, about:flags or the command line. The browser will fall back to software compositing and hardware acceleration will be unavailable.</a><br style="box-sizing: border-box; user-select: text;"><i style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Disabled Features:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">gpu_compositing</span></i></li><li style="box-sizing: border-box; user-select: text;"><a style="box-sizing: border-box; user-select: text;">GPU process was unable to boot: GPU process crashed too many times with SwiftShader.</a><br style="box-sizing: border-box; user-select: text;"><i style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Disabled Features:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">all</span></i></li></ul></div><div id="log-messages" jsdisplay="values.length" jstcache="1" style="box-sizing: border-box; user-select: text; margin-bottom: 1em; color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3 jstcache="0" style="box-sizing: border-box; user-select: text; margin-bottom: 0px; margin-top: 0px;">Log Messages</h3><ul jstcache="0" style="box-sizing: border-box; user-select: text; margin-bottom: 0px; margin-top: 0px;"><li jsselect="values" jstcache="2" jsinstance="0" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">GpuProcessHost</span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">The GPU process exited normally. Everything is okay.</span></li><li jsselect="values" jstcache="2" jsinstance="1" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">GpuProcessHost</span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">The GPU process exited normally. Everything is okay.</span></li><li jsselect="values" jstcache="2" jsinstance="2" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">GpuProcessHost</span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">The GPU process exited normally. Everything is okay.</span></li><li jsselect="values" jstcache="2" jsinstance="3" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">[149:149:1123/101043.433558:ERROR:angle_platform_impl.cc(44)]<span> </span></span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">Display.cpp:894 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL</span></li><li jsselect="values" jstcache="2" jsinstance="4" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">[149:149:1123/101043.433671:ERROR:gl_surface_egl.cc(782)]<span> </span></span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL</span></li><li jsselect="values" jstcache="2" jsinstance="5" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">[149:149:1123/101043.433706:ERROR:gl_surface_egl.cc(1382)]<span> </span></span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type</span></li><li jsselect="values" jstcache="2" jsinstance="6" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">[149:149:1123/101043.433890:ERROR:angle_platform_impl.cc(44)]<span> </span></span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">Display.cpp:894 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL</span></li><li jsselect="values" jstcache="2" jsinstance="7" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">[149:149:1123/101043.433935:ERROR:gl_surface_egl.cc(782)]<span> </span></span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL</span></li><li jsselect="values" jstcache="2" jsinstance="8" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">[149:149:1123/101043.433964:ERROR:gl_surface_egl.cc(1382)]<span> </span></span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED</span></li><li jsselect="values" jstcache="2" jsinstance="9" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">[149:149:1123/101043.434005:ERROR:gl_ozone_egl.cc(20)]<span> </span></span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">GLSurfaceEGL::InitializeOneOff failed.</span></li><li jsselect="values" jstcache="2" jsinstance="10" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">[149:149:1123/101043.435104:ERROR:viz_main_impl.cc(161)]<span> </span></span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">Exiting GPU process due to errors during initialization</span></li><li jsselect="values" jstcache="2" jsinstance="11" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">GpuProcessHost</span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">The GPU process exited normally. Everything is okay.</span></li><li jsselect="values" jstcache="2" jsinstance="12" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">GpuProcessHost</span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">The GPU process exited normally. Everything is okay.</span></li><li jsselect="values" jstcache="2" jsinstance="13" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">GpuProcessHost</span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">The GPU process exited normally. Everything is okay.</span></li><li jsselect="values" jstcache="2" jsinstance="14" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">GpuProcessHost</span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">The GPU process exited normally. Everything is okay.</span></li><li jsselect="values" jstcache="2" jsinstance="15" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">[406:406:1123/101043.541074:ERROR:angle_platform_impl.cc(44)]<span> </span></span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">Display.cpp:894 (initialize): ANGLE Display::initialize error 0: Internal Vulkan error (-3): Initialization of an object could not be completed for implementation-specific reasons, in ../../third_party/angle/src/libANGLE/renderer/vulkan/RendererVk.cpp, initialize:1048.</span></li><li jsselect="values" jstcache="2" jsinstance="16" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">[406:406:1123/101043.541187:ERROR:gl_surface_egl.cc(782)]<span> </span></span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">EGL Driver message (Critical) eglInitialize: Internal Vulkan error (-3): Initialization of an object could not be completed for implementation-specific reasons, in ../../third_party/angle/src/libANGLE/renderer/vulkan/RendererVk.cpp, initialize:1048.</span></li><li jsselect="values" jstcache="2" jsinstance="17" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">[406:406:1123/101043.541226:ERROR:gl_surface_egl.cc(1382)]<span> </span></span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED</span></li><li jsselect="values" jstcache="2" jsinstance="18" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">[406:406:1123/101043.541264:ERROR:gl_ozone_egl.cc(20)]<span> </span></span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">GLSurfaceEGL::InitializeOneOff failed.</span></li><li jsselect="values" jstcache="2" jsinstance="19" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">[406:406:1123/101043.542514:ERROR:viz_main_impl.cc(161)]<span> </span></span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">Exiting GPU process due to errors during initialization</span></li><li jsselect="values" jstcache="2" jsinstance="20" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">GpuProcessHost</span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">The GPU process exited normally. Everything is okay.</span></li><li jsselect="values" jstcache="2" jsinstance="21" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">[474:474:1123/101043.567722:WARNING:vaapi_wrapper.cc(611)]<span> </span></span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">VAAPI video acceleration not available for disabled</span></li><li jsselect="values" jstcache="2" jsinstance="*22" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">[474:474:1123/101043.567838:ERROR:gpu_init.cc(457)]<span> </span></span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">Passthrough is not supported, GL is disabled, ANGLE is</span></li></ul></div>
</details>

**Comment by apawelec** [comment]
> Is VAAPI still not working in chromium flatpak? I have a .rpm Chromium that works fine but when I use the same flags in the Flatpak it doesn't seem to work. If anyone has it working... how?

It worked fine for me until the last update of 98.x ...

**Comment by wooque** [comment]
For Chromium 98+ you need ` --disable-features=UseChromeOSDirectVideoDecoder` as well

**Comment by chaibronz** [comment]
> For Chromium 98+ you need ` --disable-features=UseChromeOSDirectVideoDecoder` as well

Working now, thanks! On a side note, how do people keep up with all the required flag changes?

**Comment by refi64** [comment]
This seems to be because [the new VA-API decoder requires Vulkan](https://bugs.chromium.org/p/chromium/issues/detail?id=1236697), but that's non-functioning here right now. `--disable-features=UseChromeOSDirectVideoDecoder` uses the old VA-API code path, which has no Vulkan dependency, but:

- is slower
- will likely be removed at some point in the future

Relevant comment in question:

> It's because while VDAVideoDecoder uses hardware acceleration, it still makes copies of the whole frame, so it's not quite as much of a perf/power gain as VaapiVideoDecoder (which requires vulkan). We're eventually planning on getting rid of the non vulkan path so we only have to support one implementation that works with both generic Linux as well as chromeos

**Comment by Schlipak** [comment]
To report here again, since my last comment VA-API hadn't been working and I had no WEBGL features available since then. (They were working in a regular .deb Chrome)
I just got an update for Chromium 98.0.4758.80 and suddenly it works again. :tada: 
I did add the `--disable-features=UseChromeOSDirectVideoDecoder` flag yesterday but to no avail, now VA-API seems to work even without it.

**Comment by refi64** [comment]
Perfect, that means #201 did the trick here.

**Comment by vulongm** [comment]
Is it possible to get video decode with Vulkan currently?

Using these flags it seems to be working for me
```
--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy
--enable-features=VaapiVideoDecoder
--use-gl=egl
--disable-features=UseChromeOSDirectVideoDecoder
```

However with the Vulkan one it's using FFmpegVideoDecoder.
```
--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy
--enable-features=VaapiVideoDecoder,Vulkan
--use-gl=egl
```

**Comment by refi64** [comment]
@vulongm there are still various open things with the new video decoder that uses Vulkan, did you check for something interesting printed in the logs? Maybe try dropping `--use-gl=egl`?

**Comment by vulongm** [comment]
@refi64 Dropping ``--user-gl=egl`` removes the decodes from ``chrome://gpu`` and doesn't seem to be working.
I do see this with the flag in when starting the browser, but not much else when the video is playing.
```
34:34:0228/170035.921732:ERROR:gpu_init.cc(454)] Passthrough is not supported, GL is egl, ANGLE is 
[34:34:0228/170035.985154:ERROR:sandbox_linux.cc(385)] InitializeSandbox() called with multiple threads in process gpu-process.
[34:34:0228/170035.987578:ERROR:vulkan_device_queue.cc(227)] Vulkan: AMD RADV RAVEN
```

**Comment by tinywrkb** [comment]
VAAPI has been broken for me in Chromium and derived browsers for a while now, and I looked at this again today, testing Chromium 98.0.4758.102.

Intel Broadwell, mesa 21.3.5, libva 2.13.0, `LIBVA_DRIVER_NAME=i965`.
Vulkan is unusable, enabling it breaks Chromium, the UI is completely frozen.
With XWayland, I can get VAAPI working by add `--use-gl=egl`, `--disable-features=UseChromeOSDirectVideoDecoder`, and `--enable-features=VaapiVideoDecoder`, but it's constantly dropping frames, video is a bit choppy, and it looks like I'm hitting [this].

**Comment by Flashwalker** [comment]
https://github.com/ungoogled-software/ungoogled-chromium/issues/2346
