### ISSUE TITLE
Consider carrying the patches from chromium-wayland-vaapi for hardware accelerated decode under Wayland

### ISSUE THREAD

**Issue by jbalme** [flathub/org.chromium.Chromium#187]
There are a set of patches that appear to enable hardware-accelerated video decoding on Wayland used in the following AUR package:

https://aur.archlinux.org/packages/chromium-wayland-vaapi/

I'm unaware of the origins of these patches, but it might be something to look into for a Wayland-first experience.

**Comment by refi64** [comment]
I'm a bit hesitant to include these for two main reasons:

- Every patch we add is something that needs to be merged with new releases. I don't want to be bottlenecked on updates waiting for an external entity, but I don't know enough about VA-API internals to be rebasing them myself.
- The patch seems a bit...simplistic, especially with the randomly changed magic numbers (e.g. `+ 1` turning into `+ 3`) and given that I believe Igalia had mentioned making fully Ozone-complaint VA-API would take some internal changes. Maybe this is just a bit young and I'm overthinking it, but VA-API is definitely the type of area where individual hardware can make a huge difference, and I don't want to end up with some patches that only work in some odd subset of cases.

Now, once a patch is merged in, I'd probably backport it to a current release, but I'm not keen to keep it in otherwise atm.
