### ISSUE TITLE
YubiKey FIDO2 WebAuthn requires pcsc socket

### ISSUE THREAD

**Issue by greenbeauty** [flathub/org.chromium.Chromium#189]
WebAuthn was failing for me, falling back to OTP.

As soon as I added the pcsc socket permission, voila.

**Comment by wjt** [comment]
Can you give more details about the hardware,  platform, site you're using? I ask because with:

- Endless OS (which doesn't have pcscd)
- This Chromium at 25dfb699
- Bus 001 Device 008: ID 1050:0407 Yubico.com Yubikey 4/5 OTP+U2F+CCID

the demo at https://webauthn.io/ works fine.

**Comment by refi64** [comment]
PCSC issues can't reliably be fixed right now due to it having an unstable protocol, but I don't think it should be needed at all for PCSC.

IIRC you need to have a smart key inserted *before* opening Chromium for it to be detected atm. If I had to guess, maybe you already had it inserted when you opened the pcsc socket, so you thought that's what fixed it?

**Comment by greenbeauty** [comment]
> IIRC you need to have a smart key inserted _before_ opening Chromium for it to be detected atm. If I had to guess, maybe you already had it inserted when you opened the pcsc socket, so you thought that's what fixed it?

I think you're right. I've just run an experiment with a fresh installation, this time no pcsc - I get the same unhelpful error as before if the key is inserted and used _after_ opening Chromium. Inserting the key _before_ everything is dandy.

Thanks and sorry for taking so long to follow up. I think this issue can be closed.
