### ISSUE TITLE
PipeWire screen sharing doesn't work on F36

### ISSUE THREAD

**Issue by YaLTeR** [flathub/org.chromium.Chromium#210]
Produces blank frames and spams
```
[2:294:0316/092758.616658:ERROR:egl_dmabuf.cc(443)] Failed to record frame: Error creating EGLImageKHR - GL_NO_ERROR
```

F36, mutter and gnome-shell 42, OBS works, I have an AMD RX 580 which notably does not support modifiers yet (so it uses the invalid modifier).

**Comment by refi64** [comment]
@grulja do you have any idea if this is something that would be fixed by [this change](https://source.chromium.org/chromium/_/webrtc/src.git/+/2f194e03254cf349706bc50c6b2a1e6cd6300a5d)? Looks like the change to fix the EGL error reporting isn't in stable yet, unfortunately...I might just backport it tbh.

**Comment by refi64** [comment]
@YaLTeR Chromium 100 should be out, is this still reproducible?

**Comment by YaLTeR** [comment]
Seems like it works on the latest Flathub Chromium!
