### ISSUE TITLE
Upstream review of sandboxing code?

### ISSUE THREAD

**Issue by cjao** [flathub/org.chromium.Chromium#43]
First of all, thanks for your work in packaging this!  I notice that you have written a [patch](https://github.com/flathub/org.chromium.Chromium/blob/master/patches/0006-flatpak-Add-initial-sandbox-support.patch) to adapt Chromium to Flatpak's sandbox. Are you planning to submit this upstream for review? I appreciate your work in building this package, but it's really important to not compromise the quality of the sandbox.

**Comment by Erick555** [comment]
AFAIK upstream stated they aren't interested in adopting flatpak sandbox support atm.

**Comment by refi64** [comment]
Indeed at least for now, there is no interest in another sandbox, and I doubt the current global situation would do much to encourage this given that the Chromium team is probably still WFH.

That being said, it's worth noting Chromium's sandbox is two layers, the second being a rather strict BPF sandbox, and that one is entirely unmodified. The first layer is primarily to block filesystem access, which has been tested and confirmed to work here (partly because we've had files end up missing that we *needed* to be able to access :sweat_smile:)
