### ISSUE TITLE
Needs to be more secure

### ISSUE THREAD

**Issue by andybe** [flathub/org.chromium.Chromium#44]
Missing parts in yml

        "--filesystem=xdg-videos:ro",
        "--filesystem=xdg-pictures:ro",
        "--filesystem=xdg-download",

for more security

Thanks

**Comment by Erick555** [comment]
This doesn't add any security when `--filesystem=home` is active. The proper way is to re-enable file portal support, see https://github.com/flathub/org.chromium.Chromium/issues/33#issuecomment-739496672 .

**Comment by refi64** [comment]
For our purposes the file dialog needed to work properly, and indeed portal support is broken at the moment due to xdg-desktop-portal bugs. If you want more locked down filesystem access, just use `flatpak override` / Flatseal to remove `filesystem=home` (`--nofilesystem=home`) and then add only the directories you want.

**Comment by andybe** [comment]
@refi64 by the way. I' was unabel to build it my self.- I change the meta data "on host".
